### ISSUE TITLE
Home page frontend

### ISSUE THREAD

**Issue by jameskokoska** [UofT-Frosh-Orientation/orientation-website#102]
![image](https://user-images.githubusercontent.com/50821962/172076863-f46c40ba-1c0f-4390-928c-8084dffcaf86.png)

See Figma
- [ ] Landing page banner
- [ ] Timeline integration see #82 
- [ ] Schedule integration see #83 
- [ ] Sponsor integration see #84 
- [ ] Footer integration see #40
