### ISSUE TITLE
Scunt discord bot TODO

### ISSUE THREAD

**Issue by Cali0707** [UofT-Frosh-Orientation/orientation-website#556]
Still TODO:
- [ ] Update error handling in the bot to match this year's error format
- [ ] Add balancing algo to backend
- [ ] Test the login route with the actual bot

_Originally posted by @Cali0707 in https://github.com/UofT-Frosh-Orientation/orientation-website/issues/555#issuecomment-1239521738_
